/*
 * FreeRTOS V202212.00
 * Copyright (C) 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * https://www.FreeRTOS.org
 * https://github.com/FreeRTOS
 *
 */

/* FreeRTOS kernel includes. */
#include <stdint.h>
#include <FreeRTOS.h>
#include <task.h>
#include <riscv-virt.h>
#include <stdio.h>
#include <string.h>
#include "FreeRTOS_CLI.h"
#include "FreeRTOSFATConfig.h"
#include "ff_headers.h"
#include "ff_stdio.h"
#include "ffconf.h"
#include "ff_ramdisk.h"
#include "ff_stdio.h"
#include "ff_file.h"
#include "self_cwd.h"

/* Run a simple demo just prints 'Blink' */
#define DEMO_BLINKY    1
#define MAX_PATH 256

extern void freertos_risc_v_trap_handler( void );

void vApplicationMallocFailedHook( void );
void vApplicationIdleHook( void );
void vApplicationStackOverflowHook( TaskHandle_t pxTask,
                                    char * pcTaskName );
void vApplicationTickHook( void );

/*
 * Setup the Spike simulator to run this demo.
 */
static void prvSetupSpike( void );

int main_blinky( void );
void vShellTask( );

/*-----------------------------------------------------------*/

//uint8_t ucRAMDisk[ 512 * 520 ]; // 100KB
SD_Disk_t *sdDisk;
FF_Disk_t *pxDisk;
FF_IOManager_t *pxIOManager;

static char pcCurrentDir[MAX_PATH] = "/\0";


/*-----------------------------------------------------------*/


void vNormalizePath(char *out, const char *in)
{
    char temp[MAX_PATH];
    if(in[0] == '/')
    {
        strncpy(temp, in, MAX_PATH);
    }
    else
    {
        snprintf(temp, MAX_PATH, "%s/%s", pcCurrentDir, in);
    }

    char *tokens[32];
    int count = 0;

    char *p = strtok(temp, "/");
    while(p != NULL && count < 32)
    {
        if(strcmp(p, "..") == 0)
        {
            if(count > 0) count--;
        }
        else if(strcmp(p, ".") != 0)
        {
            tokens[count++] = p;
        }
        p = strtok(NULL, "/");
    }

    strcpy(out, "/");
    for(int i = 0; i < count; i++)
    {
        strcat(out, tokens[i]);
        if(i != count - 1) strcat(out, "/");
    }
}

static BaseType_t cmd_hello( char *writeBuffer, size_t writeBufferLen, const char *commandString) {
    snprintf(writeBuffer, writeBufferLen, "Hello World!\r\n");
    //uprint("Hello World!", 13, 2 );
    return pdFALSE;
}

static BaseType_t prvTaskStatsCommand( char *pcWriteBuffer,
                                          size_t xWriteBufferLen,
                                          const char *pcCommandString )
{
    /* For simplicity, this function assumes the output buffer is large enough
    to hold all the text generated by executing the vTaskList() API function,
    so the xWriteBufferLen parameter is not used. */
    ( void ) xWriteBufferLen;

    /* pcWriteBuffer is used directly as the vTaskList() parameter, so the table
    generated by executing vTaskList() is written directly into the output
    buffer. */
    //vTaskList( pcWriteBuffer + strlen( pcHeader ) );
    vTaskList( pcWriteBuffer );

    /* The entire table was written directly to the output buffer.  Execution
    of this command is complete, so return pdFALSE. */
    return pdFALSE;
}

static BaseType_t prvPwdCommand(char *pcWriteBuffer,
                                size_t xWriteBufferLen,
                                const char *pcCommandString)
{
    (void) pcCommandString;
    snprintf(pcWriteBuffer, xWriteBufferLen, "%s\r\n", pcCurrentDir);
    return pdFALSE;
}


static BaseType_t prvCdCommand(char *pcWriteBuffer,
                               size_t xWriteBufferLen,
                               const char *pcCommandString)
{
    const char *param;
    BaseType_t len;

    param = FreeRTOS_CLIGetParameter(pcCommandString, 1, &len);

    if(param == NULL)
    {
        snprintf(pcWriteBuffer, xWriteBufferLen, "%s\r\n", pcCurrentDir);
        return pdFALSE;
    }

    char input[256];
    strncpy(input, param, len);
    //input[len] = '\0';

    char newPath[256];
    vNormalizePath(newPath, input);

    FF_DirEnt_t xDir;

    if(FF_FindFirst(pxIOManager, &xDir, newPath) != FF_ERR_NONE)
    {
        snprintf(pcWriteBuffer, xWriteBufferLen, "cd: no such dir: %s\r\n", xDir);
        return pdFALSE;
    }

    if(!(xDir.ucAttrib & FF_FAT_ATTR_DIR))
    {
        snprintf(pcWriteBuffer, xWriteBufferLen, "cd: not a dir: %s\r\n", xDir);
        return pdFALSE;
    }

    strncpy(pcCurrentDir, newPath, sizeof(pcCurrentDir));

    snprintf(pcWriteBuffer, xWriteBufferLen, "OK\r\n");
    return pdFALSE;
}

static BaseType_t prvLsCommand(char *pcWriteBuffer,
                               size_t xWriteBufferLen,
                               const char *pcCommandString)
{
    (void) pcCommandString;
	char cbuf[128];
	int buflen = 128;
	FF_Unmount(pxDisk);
	FF_Mount(pxDisk, 0);
   	//buflen = sprintf(cbuf, "CLI stack: %u\n", uxTaskGetStackHighWaterMark(NULL));
	//uprint( cbuf, buflen, 2 );

    FF_DirEnt_t xDir;
    FF_Error_t xError;
	memset(&xDir, 0, sizeof(xDir));

   	//snprintf(cbuf, buflen, " a");
	//vSendString( cbuf );
	//uprint( " a", 2, 0 );

    size_t offset = 0;

    xError = FF_FindFirst(pxIOManager, &xDir, pcCurrentDir);
    //xError = FF_FindFirst(pxDisk->pxIOManager, &xDir, "/\0");

   	//snprintf(cbuf, buflen, "FindFirst\n");
	//vSendString( cbuf );

    if(xError != FF_ERR_NONE)
    {
		if((xError & 0xffff) != FF_ERR_DIR_END_OF_DIR) {
        	snprintf(pcWriteBuffer, xWriteBufferLen, "ls: error\r\n");
   			buflen = sprintf(cbuf, "e: %d",xError);
			uprint( cbuf, buflen, 2 );
       		return pdFALSE;
		}
		// end of dir
    }

    do
    {
        int written = snprintf(pcWriteBuffer + offset,
                               xWriteBufferLen - offset,
                               "%c %s\r\n",
                               (xDir.ucAttrib & FF_FAT_ATTR_DIR) ? 'd' : '-',
                               xDir.pcFileName);

        offset += written;

        /* バッファオーバー防止 */
        if(offset >= xWriteBufferLen - 32)
        {
            break;
        }

        //xError = FF_FindNext(pxIOManager, &xDir);
        xError = FF_FindNext(pxDisk->pxIOManager, &xDir);

    } while(xError == FF_ERR_NONE);

    return pdFALSE;
}

static BaseType_t prvMkdirCommand(char *pcWriteBuffer,
                                  size_t xWriteBufferLen,
                                  const char *pcCommandString)
{
    char param[64];
    BaseType_t paramLen;

    /* 引数取得 */
    const char *pcParam = FreeRTOS_CLIGetParameter(
        pcCommandString, 1, &paramLen);

    if(pcParam == NULL)
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "mkdir: missing operand\r\n");
        return pdFALSE;
    }

    /* コピー＆NULL終端 */
    if(paramLen >= sizeof(param))
        paramLen = sizeof(param) - 1;

    memcpy(param, pcParam, paramLen);
    param[paramLen] = '\0';

    /* フルパス生成 */
    char path[256];

    if(param[0] == '/')
    {
        snprintf(path, sizeof(path), "%s", param);
    }
    else
    {
        snprintf(path, sizeof(path), "%s/%s", pcCurrentDir, param);
    }

    /* mkdir実行 */
    FF_Error_t err = FF_MkDir(pxIOManager, path);

    if(err != FF_ERR_NONE)
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "mkdir: error (%08X)\r\n", err);
    }
    else
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "mkdir: created %s\r\n", path);
    }

    return pdFALSE;
}

static BaseType_t prvCatCommand(char *pcWriteBuffer,
                                size_t xWriteBufferLen,
                                const char *pcCommandString)
{
    FF_Error_t xError;
    char param[64];
    BaseType_t paramLen;

    /* 引数取得 */
    const char *pcParam = FreeRTOS_CLIGetParameter(
        pcCommandString, 1, &paramLen);

    if(pcParam == NULL)
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "cat: missing file\r\n");
        return pdFALSE;
    }

    /* コピー＆NULL終端 */
    if(paramLen >= sizeof(param))
        paramLen = sizeof(param) - 1;

    memcpy(param, pcParam, paramLen);
    param[paramLen] = '\0';

    /* フルパス生成 */
    char path[128];

    if(param[0] == '/')
    {
        snprintf(path, sizeof(path), "%s", param);
    }
    else
    {
        if(strcmp(pcCurrentDir, "/") == 0)
            snprintf(path, sizeof(path), "/%s", param);
        else
            snprintf(path, sizeof(path), "%s/%s", pcCurrentDir, param);
    }

    /* ファイルオープン */
    //FF_FILE *fp = FF_Open(pxIOManager, path, FF_MODE_READ);
	FF_FILE *fp = FF_Open(pxIOManager,
	                      path,
	                      FF_MODE_READ,
	                      &xError);

    if(fp == NULL)
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "cat: cannot open %s\r\n", path);
        return pdFALSE;
    }

    /* 読み込みバッファ */
    unsigned char readBuf[64];
    int readBytes;

    size_t offset = 0;

    do
    {
        readBytes = FF_Read(fp, 1, sizeof(readBuf), readBuf);

        if(readBytes > 0)
        {
            /* バッファに収まる分だけコピー */
            int toCopy = readBytes;

            if(offset + toCopy >= xWriteBufferLen)
                toCopy = xWriteBufferLen - offset - 1;

            memcpy(pcWriteBuffer + offset, readBuf, toCopy);
            offset += toCopy;

            if(offset >= xWriteBufferLen - 1)
                break;
        }

    } while(readBytes > 0);

    pcWriteBuffer[offset] = '\0';

    FF_Close(fp);

    return pdFALSE;
}

static BaseType_t prvCpCommand(char *pcWriteBuffer,
                               size_t xWriteBufferLen,
                               const char *pcCommandString)
{
    char src[64], dst[64];
    BaseType_t len1, len2;

    /* 引数取得 */
    const char *p1 = FreeRTOS_CLIGetParameter(pcCommandString, 1, &len1);
    const char *p2 = FreeRTOS_CLIGetParameter(pcCommandString, 2, &len2);

    if(p1 == NULL || p2 == NULL)
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "cp: src dst\r\n");
        return pdFALSE;
    }

    /* コピー */
    if(len1 >= sizeof(src)) len1 = sizeof(src)-1;
    if(len2 >= sizeof(dst)) len2 = sizeof(dst)-1;

    memcpy(src, p1, len1); src[len1] = '\0';
    memcpy(dst, p2, len2); dst[len2] = '\0';

    /* パス生成 */
    char pathSrc[128], pathDst[128];

    if(src[0] == '/')
        snprintf(pathSrc, sizeof(pathSrc), "%s", src);
    else
        snprintf(pathSrc, sizeof(pathSrc), "%s/%s", pcCurrentDir, src);

    if(dst[0] == '/')
        snprintf(pathDst, sizeof(pathDst), "%s", dst);
    else
        snprintf(pathDst, sizeof(pathDst), "%s/%s", pcCurrentDir, dst);

    /* open src */
    FF_Error_t err;
    FF_FILE *fpSrc = FF_Open(pxIOManager, pathSrc, FF_MODE_READ, &err);

    if(fpSrc == NULL)
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "cp: open src error (%08X)\r\n", err);
        return pdFALSE;
    }

    /* open dst */
    FF_FILE *fpDst = FF_Open(pxIOManager, pathDst,
                             FF_MODE_WRITE | FF_MODE_CREATE | FF_MODE_TRUNCATE,
                             &err);

    if(fpDst == NULL)
    {
        FF_Close(fpSrc);
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "cp: open dst error (%08X)\r\n", err);
        return pdFALSE;
    }

    /* コピー */
    uint8_t buf[128];
    int32_t r;

    do
    {
        r = FF_Read(fpSrc, 1, sizeof(buf), buf);

        if(r > 0)
        {
            int32_t w = FF_Write(fpDst, 1, r, buf);

            if(w != r)
            {
                snprintf(pcWriteBuffer, xWriteBufferLen,
                         "cp: write error\r\n");
                break;
            }
        }

    } while(r > 0);

    FF_Close(fpSrc);
    FF_Close(fpDst);

    snprintf(pcWriteBuffer, xWriteBufferLen,
             "cp: done\r\n");

    return pdFALSE;
}

static BaseType_t prvRmCommand(char *pcWriteBuffer,
                               size_t xWriteBufferLen,
                               const char *pcCommandString)
{
    char param[64];
    BaseType_t paramLen;

    const char *pcParam = FreeRTOS_CLIGetParameter(
        pcCommandString, 1, &paramLen);

    if(pcParam == NULL)
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "rm: missing operand\r\n");
        return pdFALSE;
    }

    if(paramLen >= sizeof(param))
        paramLen = sizeof(param) - 1;

    memcpy(param, pcParam, paramLen);
    param[paramLen] = '\0';

    /* パス生成 */
    char path[128];

    if(param[0] == '/')
    {
        snprintf(path, sizeof(path), "%s", param);
    }
    else
    {
        if(strcmp(pcCurrentDir, "/") == 0)
            snprintf(path, sizeof(path), "/%s", param);
        else
            snprintf(path, sizeof(path), "%s/%s", pcCurrentDir, param);
    }

    /* 削除 */
    FF_Error_t err = FF_RmFile(pxIOManager, path);

    if(err != FF_ERR_NONE)
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "rm: error (%08X)\r\n", err);
    }
    else
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "rm: deleted %s\r\n", path);
    }

    return pdFALSE;
}

static BaseType_t prvRmdirCommand(char *pcWriteBuffer,
                                  size_t xWriteBufferLen,
                                  const char *pcCommandString)
{
    char param[64];
    BaseType_t paramLen;

    /* 引数取得 */
    const char *pcParam = FreeRTOS_CLIGetParameter(
        pcCommandString, 1, &paramLen);

    if(pcParam == NULL)
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "rmdir: missing operand\r\n");
        return pdFALSE;
    }

    /* コピー */
    if(paramLen >= sizeof(param))
        paramLen = sizeof(param) - 1;

    memcpy(param, pcParam, paramLen);
    param[paramLen] = '\0';

    /* フルパス生成 */
    char path[128];

    if(param[0] == '/')
    {
        snprintf(path, sizeof(path), "%s", param);
    }
    else
    {
        if(strcmp(pcCurrentDir, "/") == 0)
            snprintf(path, sizeof(path), "/%s", param);
        else
            snprintf(path, sizeof(path), "%s/%s", pcCurrentDir, param);
    }

    /* 削除 */
    FF_Error_t err = FF_RmDir(pxIOManager, path);

    if(err != FF_ERR_NONE)
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "rmdir: error (%08X)\r\n", err);
    }
    else
    {
        snprintf(pcWriteBuffer, xWriteBufferLen,
                 "rmdir: removed %s\r\n", path);
    }

    return pdFALSE;
}

static const CLI_Command_Definition_t hello_cmd = {
    "hello",
    "hello: print hello message\n",
    cmd_hello,
    0
};

static const CLI_Command_Definition_t ps_cmd = {
    "ps",
    "ps: list of task\n",
    prvTaskStatsCommand,
    0
};

static const CLI_Command_Definition_t xPwd =
{
    "pwd",
    "pwd: show current dir\r\n",
    prvPwdCommand,
    0
};

static const CLI_Command_Definition_t xCd =
{
    "cd",
    "cd <dir>: change dir\r\n",
    prvCdCommand,
    1
};

static const CLI_Command_Definition_t xLs =
{
    "ls",
    "ls: list files\r\n",
    prvLsCommand,
    0
};

static const CLI_Command_Definition_t xMkdir =
{
    "mkdir",
    "mkdir <dir>: change dir\r\n",
    prvMkdirCommand,
    1
};

static const CLI_Command_Definition_t xCat =
{
    "cat",
    "cat <file>: print file contents\r\n",
    prvCatCommand,
    1
};

static const CLI_Command_Definition_t xCp =
{
    "cp",
    "cp <file> <file>: copy file\r\n",
    prvCpCommand,
    2
};

static const CLI_Command_Definition_t xRm =
{
    "rm",
    "rm <file>: remove file\r\n",
    prvRmCommand,
    1
};

static const CLI_Command_Definition_t xRmdir =
{
    "rmdir",
    "rmdir <dir>: remove directory\r\n",
    prvRmdirCommand,
    1
};

/*-----------------------------------------------------------*/
/*-----------------------------------------------------------*/

int main( void )
{
    int ret;

    prvSetupSpike();

	//register_commands;
	FreeRTOS_CLIRegisterCommand(&hello_cmd);
	FreeRTOS_CLIRegisterCommand(&ps_cmd);
    FreeRTOS_CLIRegisterCommand(&xPwd);
    FreeRTOS_CLIRegisterCommand(&xCd);
    FreeRTOS_CLIRegisterCommand(&xLs);
    FreeRTOS_CLIRegisterCommand(&xMkdir);
    FreeRTOS_CLIRegisterCommand(&xRmdir);
    FreeRTOS_CLIRegisterCommand(&xCat);
    FreeRTOS_CLIRegisterCommand(&xCp);
    FreeRTOS_CLIRegisterCommand(&xRm);

	uprint("pxDisk init",11,2);
	pxDisk = FF_RAMDiskInit( "/",
                              NULL,
                              4096 * 4,
                              1024 );

	if (pxDisk == NULL) {
		uprint("no pxDisk",9,2);
	}
	else {
		uprint("OK pxDisk",9,2);
	}
	pxIOManager = pxDisk->pxIOManager;

    #if defined( DEMO_BLINKY )
        ret = main_blinky();
    #else
    #error "Please add or select demo."
    #endif

    return ret;
}
/*-----------------------------------------------------------*/
static void prvSetupSpike( void )
{
    __asm__ volatile ( "csrw mtvec, %0" : : "r" ( freertos_risc_v_trap_handler ) );
}

/*-----------------------------------------------------------*/

void vApplicationMallocFailedHook( void )
{
    /* vApplicationMallocFailedHook() will only be called if
     * configUSE_MALLOC_FAILED_HOOK is set to 1 in FreeRTOSConfig.h.  It is a hook
     * function that will get called if a call to pvPortMalloc() fails.
     * pvPortMalloc() is called internally by the kernel whenever a task, queue,
     * timer or semaphore is created.  It is also called by various parts of the
     * demo application.  If heap_1.c or heap_2.c are used, then the size of the
     * heap available to pvPortMalloc() is defined by configTOTAL_HEAP_SIZE in
     * FreeRTOSConfig.h, and the xPortGetFreeHeapSize() API function can be used
     * to query the size of free heap space that remains (although it does not
     * provide information on how the remaining heap might be fragmented). */
    taskDISABLE_INTERRUPTS();

    for( ; ; )
    {
    }
}
/*-----------------------------------------------------------*/

void vApplicationIdleHook( void )
{
    /* vApplicationIdleHook() will only be called if configUSE_IDLE_HOOK is set
     * to 1 in FreeRTOSConfig.h.  It will be called on each iteration of the idle
     * task.  It is essential that code added to this hook function never attempts
     * to block in any way (for example, call xQueueReceive() with a block time
     * specified, or call vTaskDelay()).  If the application makes use of the
     * vTaskDelete() API function (as this demo application does) then it is also
     * important that vApplicationIdleHook() is permitted to return to its calling
     * function, because it is the responsibility of the idle task to clean up
     * memory allocated by the kernel to any task that has since been deleted. */
}
/*-----------------------------------------------------------*/

void vApplicationStackOverflowHook( TaskHandle_t pxTask,
                                    char * pcTaskName )
{
    ( void ) pcTaskName;
    ( void ) pxTask;

    /* Run time stack overflow checking is performed if
     * configCHECK_FOR_STACK_OVERFLOW is defined to 1 or 2.  This hook
     * function is called if a stack overflow is detected. */
    taskDISABLE_INTERRUPTS();

    for( ; ; )
    {
    }
}
/*-----------------------------------------------------------*/

void vApplicationTickHook( void )
{
}
/*-----------------------------------------------------------*/

void vAssertCalled( void )
{
    volatile uint32_t ulSetTo1ToExitFunction = 0;

    taskDISABLE_INTERRUPTS();

    while( ulSetTo1ToExitFunction != 1 )
    {
        __asm volatile ( "NOP" );
    }
}
